version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    container_name: db-mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: db-postgres
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  app:
    container_name: app_simulator
    image: app
    restart: always
    build: ./gate-simulator
    ports:
      - "9999:9999"
    links:
      - mysql
      - postgres
