version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
      image: postgresql:13-alpine
      ports:
        - '5432:5432'
      volumes:
        - ./data:/var/lib/postgresql
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=pass